server:
  port: 8761
eureka:
  client:
    instance:
      hostname: localhost
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  security:
    user:
      name: ${EUREKA_USER}
      password: ${EUREKA_PASSWORD}

logging:
  level:
    root: debug
    me:
      sonam: info