server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
spring:
  security:
    user:
      name: ${EUREKA_USER}
      password: ${EUREKA_PASSWORD}

logging:
  level:
    root: debug
    me:
      sonam: info