server:
  port: 8761
eureka:
  client:
    instance:
      hostname: ${HOSTNAME}
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: ${DEFAULT_ZONE}

spring:
  main:
    allow-bean-definition-overriding: true
  security:
    user:
      name: ${EUREKA_USER}
      password: ${EUREKA_PASSWORD}

logging:
  level:
    root: info
    me:
      sonam: info