server:
  port: 8761
eureka:
  client:
    instance:
      hostname: discovery-service.sonam.cloud
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: https://discovery-service.sonam.cloud/eureka

spring:
  main:
    allow-bean-definition-overriding: true
  security:
    user:
      name: ${EUREKA_USER}
      password: ${EUREKA_PASSWORD}

logging:
  level:
    root: debug
    me:
      sonam: info